name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Prepare modules
      run: go mod tidy

    - name: Build
      run: CGO_ENABLED=0 go build -ldflags="-s -w" -o ./Fish-Telegram-Captcha-Bot ./

    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
          name: build
          path: ./Fish-Telegram-Captcha-Bot
